# Generated by Django 5.1.7 on 2025-05-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0018_delivery_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='eol_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
