# Generated by Django 5.1.7 on 2025-05-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_inventory', '0019_asset_eol_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='storage_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
    ]
