# Generated by Django 5.1.7 on 2025-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0019_asset_eol_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
    ]
