# Generated by Django 6.0.4 on 2026-06-29 06:02

import django.db.migrations.operations.special
import django.db.models.deletion
import mptt.fields
import taggit.managers
from django.db import migrations, models

import utilities.json


def rebuild_tree(apps, schema_editor):
    InventoryItemGroup = apps.get_model('netbox_inventory_plus', 'InventoryItemGroup')

    if hasattr(InventoryItemGroup, '_tree_manager'):
        InventoryItemGroup._tree_manager.rebuild()


class Migration(migrations.Migration):

    replaces = [('netbox_inventory_plus', '0001_initial_prod'), ('netbox_inventory_plus', '0002_alter_asset_serial'), ('netbox_inventory_plus', '0003_add_inventoryitemgroup'), ('netbox_inventory_plus', '0004_inventoryitemgroup_tree'), ('netbox_inventory_plus', '0005_delivery_asset_delivery'), ('netbox_inventory_plus', '0006_purchase_status'), ('netbox_inventory_plus', '0007_alter_asset_unique_together_and_more'), ('netbox_inventory_plus', '0008_alter_asset_device_type_alter_asset_module_type'), ('netbox_inventory_plus', '0009_add_rack'), ('netbox_inventory_plus', '0010_asset_description_inventoryitemtype_description'), ('netbox_inventory_plus', '0011_bom'), ('netbox_inventory_plus', '0012_asset_bom'), ('netbox_inventory_plus', '0013_bom_purchase'), ('netbox_inventory_plus', '0014_remove_bom_purchase_purchase_boms'), ('netbox_inventory_plus', '0015_alter_delivery_options_and_more'), ('netbox_inventory_plus', '0016_courier'), ('netbox_inventory_plus', '0017_transfer_asset_transfer_and_more'), ('netbox_inventory_plus', '0018_delivery_delivery_location'), ('netbox_inventory_plus', '0019_asset_eol_date'), ('netbox_inventory_plus', '0020_asset_storage_site_delivery_delivery_site_and_more')]

    initial = True

    dependencies = [
        ('dcim', '0161_cabling_cleanup'),
        ('dcim', '0187_alter_device_vc_position'),
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0077_customlink_extend_text_and_url'),
        ('extras', '0092_delete_jobresult'),
        ('extras', '0122_charfield_null_choices'),
        ('tenancy', '0007_contact_link'),
        ('tenancy', '0010_tenant_relax_uniqueness'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='netbox_inventory_plus.supplier')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['supplier', 'name'],
                'unique_together': {('supplier', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('model', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventoryitem_types', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
                'unique_together': {('manufacturer', 'model'), ('manufacturer', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('asset_tag', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('status', models.CharField(max_length=30)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.contact')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset', to='dcim.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.devicetype')),
                ('inventoryitem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset', to='dcim.inventoryitem')),
                ('inventoryitem_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_inventory_plus.inventoryitemtype')),
                ('module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset', to='dcim.module')),
                ('module_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.moduletype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory_plus.purchase')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('device_type', 'module_type', 'inventoryitem_type', 'serial'),
                'unique_together': {('device_type', 'serial'), ('inventoryitem_type', 'serial'), ('module_type', 'serial'), ('owner', 'asset_tag')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
                ('lft', models.PositiveIntegerField(default=0, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_inventory_plus.inventoryitemgroup')),
                ('rght', models.PositiveIntegerField(default=0, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitemtype',
            name='inventoryitem_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryitem_types', to='netbox_inventory_plus.inventoryitemgroup'),
        ),
        migrations.RunPython(
            code=rebuild_tree,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='inventoryitemgroup',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='netbox_inventory_plus_inventoryitemgroup_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitemgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='netbox_inventory_plus_inventoryitemgroup_name', violation_error_message='A top-level group with this name already exists.'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='netbox_inventory_plus.purchase')),
                ('receiving_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='tenancy.contact')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
                'ordering': ['purchase', 'name'],
                'unique_together': {('purchase', 'name')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory_plus.delivery'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='closed', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('device_type', 'serial'), name='unique_device_type_serial'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('module_type', 'serial'), name='unique_module_type_serial'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('inventoryitem_type', 'serial'), name='unique_inventoryitem_type_serial'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('owner', 'asset_tag'), name='unique_owner_asset_tag'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(models.F('asset_tag'), condition=models.Q(('owner__isnull', True)), name='unique_asset_tag', violation_error_message='Asset with this Asset Tag and no Owner already exists.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.moduletype'),
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('device_type', 'module_type', 'inventoryitem_type', 'rack_type', 'serial')},
        ),
        migrations.AddField(
            model_name='asset',
            name='rack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset', to='dcim.rack'),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.racktype'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('rack_type', 'serial'), name='unique_rack_type_serial'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitemtype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory_plus.bom'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='boms',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='netbox_inventory_plus.bom'),
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchases',
            field=models.ManyToManyField(related_name='orders', to='netbox_inventory_plus.purchase'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='purchase',
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('shipping_number', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(max_length=30)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='netbox_inventory_plus.courier')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='dcim.location')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='tenancy.contact')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='tenancy.contact')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('sender', 'pickup_date'),
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory_plus.transfer'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('shipping_number',), name='unique_shipping_number', violation_error_message='Transfer with this Shipping Number already exists.'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='eol_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
    ]
