# Generated by Django 6.0.4 on 2026-06-25 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory_plus', '0020_asset_storage_site_delivery_delivery_site_and_more'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
    ]
